// Registers the service worker generated by vite-plugin-pwa. Import this
// once from main.tsx in production; safe no-op during dev since devOptions
// are disabled in vite.config.ts.

export function registerServiceWorker() {
  if (import.meta.env.PROD) {
    import("virtual:pwa-register")
      .then(({ registerSW }) => {
        registerSW({ immediate: true });
      })
      .catch(() => {
        // vite-plugin-pwa not active in this build mode — safe to ignore
      });
  }
}
